{% set name = "tempo2" %}
{% set version = "2020.04.1" %}

package:
    name: "{{ name|lower }}"
    version: "{{ version }}"

source:
    # eg, https://bitbucket.org/psrsoft/tempo2/downloads/tempo2-2019.01.1.tar.gz
    #url: "https://bitbucket.org/psrsoft/{{ name }}/downloads/{{ name }}-{{ version }}.tar.gz"
    ## This is v2020.04.1 but not tagged
    url: "https://bitbucket.org/psrsoft/{{ name }}/downloads/8e8d645ba800.tar.gz"
    sha256: be22a26acb4039f4a62b9e8c016e69cac52dc1a04881e9fb84f6c70392a6f383
        
build:
    number: 1

test:
    source_files:
        - tests/test_data/test_de430.par
        - tests/test_data/test_de430.tim
    commands:
        - tempo2 -f tests/test_data/test_de430.par tests/test_data/test_de430.tim

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}
        - autoconf
        - automake
        - libtool
    host:
        - cfitsio
        - pgplot
        - gsl
        - fftw
        - libblas
        - libcblas
        - liblapack
    run:
        - cfitsio
        - pgplot
        - gsl
        - fftw
        - libblas
        - libcblas
        - liblapack
        - tempo-clockfiles
